#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AutoExpense.Android.Resource", IsApplication=true)]

namespace AutoExpense.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "12.3.0.26")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int com_google_android_gms_fonts_certs = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int com_google_android_gms_fonts_certs_dev = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int com_google_android_gms_fonts_certs_prod = 2130771970;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorCardBackGround = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorGray = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int colorGreen = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int colorMainBackGround = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int colorPink = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int colorPrimary = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int colorPrimaryDark = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int colorSecondary = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int colorWhiteGray = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int ic_launcher_background = 2130837514;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int card_corner_default = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int card_corner_large = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_icon_size = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int margin_padding_size_large = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int margin_padding_size_medium = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int margin_padding_size_micro = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int margin_padding_size_small = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int notification_icon_size = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int notification_margin_size = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int standard_icon_size = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int standard_touch_size = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int text_size_large = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int text_size_medium = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int text_size_micro = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int text_size_small = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int text_size_xlarge = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int text_size_xxlarge = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int text_size_xxxlarge = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int text_size_xxxxlarge = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int toolbar_icon_size = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int toolbar_margin_size = 2130903060;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int headshot = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_arrow_down = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_baseline_arrow_back_24 = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ic_button_background_gradient = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_button_background_green = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int ic_button_gradient_background = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int ic_circle = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int ic_circle_selected = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ic_delete = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ic_import_transactions = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ic_launcher_foreground = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_settings = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ic_sort = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ic_stripes_background = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ic_sync = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int ic_sync_green = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int ic_sync_problem = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int ic_ynab = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int primary_color_button_round = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int rounded_corner_address = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int rounded_frame = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int secondary_color_button_round = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int syncfusion_edittext_style = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int top_round_corners = 2130968599;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F050000
			public const int poppins = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int poppins_extralight = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int poppins_semibold = 2131034114;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int action_sync_all = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int amount = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int budgets_radioGroup = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int cancel_button = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int controls_constraint_layout = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int date_time_textView = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int delete_imageView = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int frameLayout = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int import_card = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int left_guideline = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int left_inner_guideline = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int name_textView = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int profile_pic_imageView = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int right_guideline = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int right_inner_guideline = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int save_settings_button = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int selected_view = 2131099664;
			
			// aapt resource value: 0x7F060013
			public const int senders_button = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int senders_recyclerView = 2131099668;
			
			// aapt resource value: 0x7F060011
			public const int sender_checkbox = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int sender_textView = 2131099666;
			
			// aapt resource value: 0x7F060015
			public const int settings_imageView = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int settings_toolbar = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int sf_data_form = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int sort_imageView = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int status_cardView = 2131099673;
			
			// aapt resource value: 0x7F06001C
			public const int synced_messages_textView = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int syncing_progress_bar = 2131099677;
			
			// aapt resource value: 0x7F06001A
			public const int sync_button = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int sync_problem_imageView = 2131099675;
			
			// aapt resource value: 0x7F06001E
			public const int textView = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int textView1 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int textView2 = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int textView3 = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int textView4 = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int time_of_day_textView = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int top_guideline = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int total_messages_textView = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int transactions_recyclerView = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int update_button = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int use_default_button = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int view = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int view2 = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int view3 = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int view4 = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int ynab_card = 2131099693;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int activity_main = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int dialog_senders = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int dialog_ynab = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int fragment_settings = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int item_sender = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int item_transaction = 2131165189;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F080000
			public const int toolbar_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int ic_launcher_round = 2131296257;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int ToolBarText = 2131427329;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
